post_install() {
  # Disable systemd-resolved
    sed -i s/"enable systemd-resolved.service"/"disable systemd-resolved.service"/g /usr/lib/systemd/system-preset/90-systemd.preset
  # Fix GTK in Lomiri
    if [ -e /usr/bin/unity8 ]; then
        install -Dm644 "/opt/halium9-post-install/lomiri/gtk.css" "/etc/skel/.config/gtk-3.0/gtk.css"
    fi
    touch /.writable_image
}

post_upgrade() {
  # Set chassis
    hostnamectl set-chassis handset  
}
